name: CD - Deploy to Azure App Service

on:
  workflow_dispatch:  # You can also use `push`, `deployment`, or `release` if preferred

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          slot-name: production
          images: ${{ secrets.ACR_NAME }}.azurecr.io/py-app:latest
